### ISSUE TITLE
Option to reset the directory upon request

### ISSUE THREAD

**Issue by lukasrothenberger** [discopop-project/discopop-gui-vscode#42] opened 2023-11-14 00:26 UTC
If a configuration fails it is possible to end up in a state where no new run can be started, even if the underlying issue has been fixed. 
For me, this occurred when the installed DiscoPoP version did not match the required version.
For this reason, it would be nice to have the option to reset the state of a configuration to the vanilla state upon request.
This request could for example be implemented in the right-click-menu of the configuration.

A workaround for this is restarting visual studio code, which makes it not a high priority but a possible inconvenience.

**Comment by goerlibe** [comment] 2023-11-15 10:14
Since rerunning discopop deletes the build directory this _should_ not happen...

Configurations don't really have any "run-related" state. The only thing I can think of is that we change the icon to be spinning during a run. 
So unless I am understanding you wrong this seems like a bug - which I also cannot reproduce at the moment. How did the issue show up for you? You say that no new run could be started. Currently I do not disable the run button during a run (which might be good idea by the way xD), so this should always be possible. And the first action of starting a run is removing the build directory which should basically reset everything.

**Comment by lukasrothenberger** [comment] 2023-11-15 16:55
Since you can not reproduce it, let's postpone this discussion to our next meeting.

**Comment by goerlibe** [comment] 2023-12-04 13:29
if this issue is not fixed by the new configuration management, we might have to reopen, but it seems fine currently...

**Closed as completed** 2023-12-14 09:07 UTC
Labels: bug, enhancement, priority:medium
